### PR TITLE
Add fastani

### PR DESCRIPTION
**Pull request by AbdullahM0hamed**

### CODE REVIEW

**Comment by AbdullahM0hamed** [comment]
500 Internal Server Error

**Comment by Blatzar** [comment]
Add to readme

**Comment by AbdullahM0hamed** [comment]
Done.

**Comment by IguanasInPyjamas** [comment]
I'm happy with this.

**Comment by IguanasInPyjamas** [comment]
Why hasn't this been merged lol

**Comment by AbdullahM0hamed** [comment]
Updated

**Pull request merged**
