### PR TITLE
Added referer and window title to mpv

### PR DESCRIPTION
**Pull request by ArjixGamer**
as the title says i added a referer and window title to mpv so that people like me that have rich presence for mpv can showoff what they are watching instead of having it show ``playing video.mp4``

### CODE REVIEW

**Comment by ArjixGamer** [comment]
plz merge

**Comment by MichaelDavidJohnson** [comment]
As long as it works for all OS there's no reason not to merge this imo

**Comment by Blatzar** [comment]
Looks good, will do some testing later

**Comment by nate-moo** [comment]
> plz merge

*no*

**Pull request merged**
