### PR TITLE
Redid slugify regex for better titles

### PR DESCRIPTION
**Pull request by Blatzar**
Will now allow +-! and disallow the file starting with .
Didn't add ' and " to the whitelist as it's not as console friendly.

### CODE REVIEW

**Comment by ArjixGamer** [comment]
em, unless you specifically input ' and " in the code itself, that wont be a problem, python escapes those characters

**Comment by Blatzar** [comment]
> em, unless you specifically input ' and " in the code itself, that wont be a problem, python escapes those characters

I mean in terminal shell

**Comment by ArjixGamer** [comment]
image

**Comment by ArjixGamer** [comment]
oh wait, echo is not the best example

**Comment by Blatzar** [comment]
I'd like to avoid backslashes in my filenames, a consequence of ' and "
image

**Pull request merged**
