### PR TITLE
Let user change from dubbed to subbed if no episodes are found - for ryuanime and dreamanime 

### PR DESCRIPTION
**Pull request by AbdullahM0hamed**
Had this idea a long time ago, and I was told I couldn't take input from providers. But apparently I can, so here I am: bringing 2 month old ideas back to life for the sake of it.

### CODE REVIEW

**Comment by Blatzar** [comment]
no option to change from subbed to dubbed :neutral_face:

**Comment by AbdullahM0hamed** [comment]
Probably a good idea to have it just in case. Didn't consider it as a viable possibility, rip

**Comment by AbdullahM0hamed** [comment]
Done

**Comment by vn-ki** [comment]
To explain, this should be handled in `dl.py`. Click absolutely should not be improted in `sites/*` or `extractors/*`

**Pull request closed without merging**
