### PR TITLE
Updating the list functionality

### PR DESCRIPTION
**Pull request by MichaelDavidJohnson**
Jesus collaborator PR's are awkward

### CODE REVIEW

**Comment by MichaelDavidJohnson** [comment]
Now, you can set a rating and a watching status. This will be useful for the next set of PR's which will allow for list formatting, giving a user a fully functional offline watch list.

**Comment by Blatzar** [comment]
Things to fix:
Not backwards compatible.
No way to set the metadata yourself (afaik)
No way to see the metadata while in the anime menu

**Comment by MichaelDavidJohnson** [comment]
Bug - somehow the user input numbers for the values in the list comes before the sort, which causes user input problems. Laggy and I are fixing it

**Comment by MichaelDavidJohnson** [comment]
Bug has been fixed.

**Pull request merged**
