### PR TITLE
Add AnimeSuge

### PR DESCRIPTION
**Pull request by AbdullahM0hamed**

### CODE REVIEW

**Comment by Blatzar** [comment]
Fails on `anime dl "neverland" -p animesuge -u -c 1` with 404 error
<details>


```
bl@arch ~/downloads> anime -ll DEBUG dl "neverland" -p animesuge -u -c 1
2020-09-20 13:16:53 arch anime_downloader.util[119513] INFO anime-downloader 4.6.5
2020-09-20 13:16:53 arch anime_downloader.util[119513] DEBUG Platform: Linux-5.8.9-arch2-1-x86_64-with-glibc2.2.5
2020-09-20 13:16:53 arch anime_downloader.util[119513] DEBUG Python 3.8.5
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG -----
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG GET https://animesuge.io/ajax/anime/search
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG {'params': {'keyword': 'neverland'}}
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36'}
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG -----
2020-09-20 13:16:53 arch anime_downloader.session[119513] DEBUG cached request
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG https://animesuge.io/ajax/anime/search?keyword=neverland
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG /tmp/animedlgvdl1j2y/tmpwctlhqhn
+--------+------------------------------+--------+
|      2 | The Promised Neverland       |        |
|      1 | The Promised Neverland (Dub) |        |
|--------+------------------------------+--------|
|   SlNo | Title                        | Meta   |
+--------+------------------------------+--------+
2020-09-20 13:16:53 arch anime_downloader.util[119513] INFO Selected The Promised Neverland (Dub)
2020-09-20 13:16:53 arch anime_downloader.sites.anime[119513] INFO Extracting episode info from page
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG -----
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG GET https://animesuge.io/anime/the-promised-neverland-dub-nln8
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG {}
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36'}
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG -----
2020-09-20 13:16:53 arch anime_downloader.session[119513] DEBUG cached request
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG https://animesuge.io/anime/the-promised-neverland-dub-nln8
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG /tmp/animedlgvdl1j2y/tmpyaoa7ad9
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG -----
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG GET https://animesuge.io/ajax/anime/servers
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG {'params': {'id': 'nln8'}}
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36'}
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG -----
2020-09-20 13:16:53 arch anime_downloader.session[119513] DEBUG cached request
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG https://animesuge.io/ajax/anime/servers?id=nln8
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG /tmp/animedlgvdl1j2y/tmp5rgm1861
2020-09-20 13:16:53 arch anime_downloader.sites.anime[119513] DEBUG EPISODE IDS: length: 12, ids: ['https://animesuge.io/anime/the-promised-neverland-dub-nln8/ep-1', 'https://animesuge.io/anime/the-promised-neverland-dub-nln8/ep-2', 'https://animesuge.io/anime/the-promised-neverland-dub-nln8/ep-3', 'https://animesuge.io/anime/the-promised-neverland-dub-nln8/ep-4', 'https://animesuge.io/anime/the-promised-neverland-dub-nln8/ep-5', 'https://animesuge.io/anime/the-promised-neverland-dub-nln8/ep-6', 'https://animesuge.io/anime/the-promised-neverland-dub-nln8/ep-7', 'https://animesuge.io/anime/the-promised-neverland-dub-nln8/ep-8', 'https://animesuge.io/anime/the-promised-neverland-dub-nln8/ep-9', 'https://animesuge.io/anime/the-promised-neverland-dub-nln8/ep-10', 'https://animesuge.io/anime/the-promised-neverland-dub-nln8/ep-11', 'https://animesuge.io/anime/the-promised-neverland-dub-nln8/ep-12']
2020-09-20 13:16:53 arch anime_downloader.commands.dl[119513] INFO Found anime: The Promised Neverland (Dub)
2020-09-20 13:16:53 arch anime_downloader.sites.anime[119513] DEBUG Extracting stream info of id: https://animesuge.io/anime/the-promised-neverland-dub-nln8/ep-1
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG -----
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG GET https://animesuge.io/ajax/anime/servers
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG {'params': {'id': 'promised-neverland-dub-nln8', 'episode': '1'}}
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36'}
2020-09-20 13:16:53 arch anime_downloader.sites.helpers.request[119513] DEBUG -----
send: b'GET /ajax/anime/servers?episode=1&id=promised-neverland-dub-nln8 HTTP/1.1\r\nHost: animesuge.io\r\nuser-agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Date: Sun, 20 Sep 2020 11:18:19 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d3b44ffe0aa2d3838737dd4f23065ca991600600699; expires=Tue, 20-Oct-20 11:18:19 GMT; path=/; domain=.animesuge.io; HttpOnly; SameSite=Lax
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: 054cd58b470000f16676a6f200000001
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 5d5b25253a8ff166-ARN
header: Content-Encoding: gzip
2020-09-20 13:16:53 arch anime_downloader.session[119513] DEBUG uncached request
Traceback (most recent call last):
  File "/home/bl/.local/bin/anime", line 8, in <module>
    sys.exit(main())
  File "/home/bl/.local/lib/python3.8/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/home/bl/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/bl/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/bl/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bl/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bl/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/bl/.local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/bl/.local/lib/python3.8/site-packages/anime_downloader/commands/dl.py", line 123, in command
    for episode in animes:
  File "/home/bl/.local/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 198, in __iter__
    yield episode_class(ep_id[1], parent=self, ep_no=ep_id[0])
  File "/home/bl/.local/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 295, in __init__
    try_data()
  File "/home/bl/.local/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 291, in try_data
    self.get_data()
  File "/home/bl/.local/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 351, in get_data
    self._sources = self._get_sources()
  File "/home/bl/.local/lib/python3.8/site-packages/anime_downloader/sites/animesuge.py", line 44, in _get_sources
    data_sources = json.loads(helpers.soupify(helpers.get("https://animesuge.io/ajax/anime/servers",
  File "/home/bl/.local/lib/python3.8/site-packages/anime_downloader/sites/helpers/request.py", line 83, in setup_func
    res.raise_for_status()
  File "/home/bl/.local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://animesuge.io/ajax/anime/servers?episode=1&id=promised-neverland-dub-nln8
bl@arch ~/downloads> 
```
</details>

**Comment by AbdullahM0hamed** [comment]
Was due to regex catching `promised-neverland-dub-nln8` instead of just `nln8`. Fixed now

**Comment by Blatzar** [comment]
I think it's best to add time.sleep() to prevent spamming

image

**Comment by AbdullahM0hamed** [comment]
Ran through all the anime from that search, didn't get a 503.

So I went and did:

```
for i in {1..10}
do
    anime dl "invaded" -P animesuge -u -c 1
done```

And it still didn't give me any 503s. Feel free to just commit `time.sleep` if you feel that it's absolutely necessary.

**Pull request merged**
