### PR TITLE
Specify to download sub only

### PR DESCRIPTION
**Pull request by mcj64**
downloader may obtain link from faststream provider which the link does not work or obtain link that downloads dubbed version of the anime

### CODE REVIEW

**Comment by andrewlef** [comment]
Forcing the app to download subs only is not a good design.  Can you implement a design that would enable to user to choose between sub and dub?

**Comment by mcj64** [comment]
> Forcing the app to download subs only is not a good design. Can you implement a design that would enable to user to choose between sub and dub?

You would need to ask vn-ki or the person who added animeflix since that would need to change many things which i am cant do as a beginner in programming. One thing though is that animeflix mix both sub and dub version of the anime in a same api link so you gonna have either ones when requesting from the api.

**Comment by MichaelDavidJohnson** [comment]
Can this be closed due to inactivity.

**Comment by Blatzar** [comment]
Closed due to inactivity

**Comment by Blatzar** [comment]
Close

**Comment by MichaelDavidJohnson** [comment]
Close

**Pull request closed without merging**
