### PR TITLE
Fixes AnimePahe and Kwik

### PR DESCRIPTION
**Pull request by ngomile**
animepahe updated the way its API is used. I've updated animepahe to account for this and also made some minor fixes and code clean up here and there. This should #300 but now the remaining thing is kwik which hopefully #290 handles.

### CODE REVIEW

**Comment by vn-ki** [comment]
I heard that kwik added captcha(?) This means animepahe is dead right? Pinging @Blatzar

**Comment by Blatzar** [comment]
Yes, there's a captcha on the download page right now. The only way to extract links now is to crack the embedded video player, since there's no captchas there (it seems), not something I can do.

**Comment by ngomile** [comment]
Not quite, the default behavior of the kwik extractor replaces the e in the url with f. So https://kwik.cx/e/n9SsxBkUPN95 becomes https://kwik.cx/f/n9SsxBkUPN95 but as you are about to see in the screenshot if we keep the e it responds correctly.

Capture

This minor tweak should rectify the problem, the captcha doesn't seem to be there anymore either. You can see if the html from the request matches with the kwik page in your browser and from what I saw it does.

**Comment by Blatzar** [comment]
Woah, guess I'll look into it once I solved all my pull requests

**Comment by Blatzar** [comment]
using kwik/e/ I can get an m3u file which mpv fails to play (probably due to referrers)
my kwik.py:
```
import logging
import re
from anime_downloader.extractors.base_extractor import BaseExtractor
from anime_downloader.sites import helpers
import anime_downloader.util as util
logger = logging.getLogger(__name__)

class Kwik(BaseExtractor):
    def _get_data(self):
        print(self.url)
        site = (helpers.get(self.url, referer = self.url, cf = True))
        regex = r"(eval[\W\w]*?)<\/script>"
        javascript = re.search(regex,site.text).group(1)
        deobfuscated = util.deobfuscate_packed_js(javascript)
        regex = r"const source='([^']*)"
        stream = re.search(regex,deobfuscated).group(1)
        return {
            'stream_url': stream,
            'referer': self.url
        }
```

**Comment by ngomile** [comment]
But that confirms it is still working yes?

**Comment by Blatzar** [comment]
Working (ish), What's left to figure out is how to get the m3u file to a playable mp4. (If the m3u file is even correct, I haven't done much testing on it yet)

**Comment by ngomile** [comment]
I don't know much about m3u files either but from doing some Google searches I arrived at [this](https://en.wikipedia.org/wiki/M3U). So from what I have read, perhaps opening it and looking at the contents will lead to the actual url though I am not sure.

**Comment by ngomile** [comment]
Animepahe is likely a lost cause, closing pull request.

**Comment by vn-ki** [comment]
@ngomile look like cloudscraper (https://pypi.org/project/cloudscraper/) works. Can you modify anime-dl to use that and try animepahe again?

**Comment by ngomile** [comment]
Are you using the latest version of Python with it? I'm kind of outdated so requesting https://kwik.cx/e/4tcRdUEckfJx with referer being the same url is still leading to a captcha error. So I'm thinking of updating my Python to see if it makes a difference.

**Comment by vn-ki** [comment]
I didn't specifically tried kwik. Can you try cloudscraper outside of anime dl and see if that works?

**Comment by ngomile** [comment]
Capture
I tried it out and this is what happened, if anyone has a newer installation of Python they should test it and see what happens. I'm a little reluctant to upgrade at the moment.

**Comment by uali6981** [comment]
> Capture
> I tried it out and this is what happened, if anyone has a newer installation of Python they should test it and see what happens. I'm a little reluctant to upgrade at the moment.

Last time when I check this out I also got this error. I didn't check now because didn't have laptop at this time. On that time I thought some dependencies error becuse on `cfscrape` when you check version the `reqiured by` field fill by `anime-downloader` but when I replace this by `cloudscraper` and check `cloudscraper` version I got that field empty.

**Comment by Blatzar** [comment]
I'm having the same issue on Python 3.8.2, however cloudscraper can successfully scrape other sites like kissanime.ru without problems.

**Comment by ngomile** [comment]
I didn't try using the recaptcha option though, seems some need to be paid for and it would probably just add bloat. So kwik is back to square one I guess.

**Comment by ngomile** [comment]
@vn-ki I've fixed kwik and pretty much this is a done deal now.

**Pull request merged**
