### PR TITLE
Added animixplay.com with both dub and sub support

### PR DESCRIPTION
**Pull request by nate-moo**

### CODE REVIEW

**Comment by AbdullahM0hamed** [comment]
https://http.cat/429

**Comment by AbdullahM0hamed** [comment]
429: Too Many PRs

**Comment by nate-moo** [comment]
I should not have said I sent the PR

**Comment by nate-moo** [comment]
I should prob sleep now before its too late

**Comment by nate-moo** [comment]
also this wasn't *extensivly* tested so there may be a few stragglers. just ping me in the discord if there are any that error out

**Comment by nate-moo** [comment]
@Blatzar fixed btw

**Pull request merged**
