### PR TITLE
Add "Disable SSL cert verifying" via options for requests (#73)

### PR DESCRIPTION
**Pull request by DeKaN**

### CODE REVIEW

**Comment by DeKaN** [comment]
I think session is better, because it automatically saves cookies between requests and also allows to set some global parameters (for example, if you need to increase timeout for specific site-provider)

**Comment by ngomile** [comment]
Adding some input, I believe making this a function and placing it in utils would be even better. Using slightly modified code from [here](https://www.peterbe.com/plog/best-practice-with-retries-with-requests), we could simply have a function:
`
import requests
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry

def request_retry(
  *args,
  retries=3,
  backoff_factor=0.3,
  status_forcelist=(500, 502, 504),
  session=None,
  verify=False,
  **kwargs,
):
    session = session or requests.Session(*args, verify=verify, **kwargs)
    retry = Retry(
       total=retries,
       read=retries,
       connect=retries,
       backoff_factor=backoff_factor,
       status_forcelist=status_forcelist,
   )
   adapter = HTTPAdapter(max_retries=retry)
   session.mount('http://', adapter)
   session.mount('https://', adapter)
   return session
`

The good thing about this approach is that it is easy to customize and there will be no need to make another file just to enable/disable ssl verifying. Function name  aside it also acts as a more resilient way to make a request without failing on first try. 

The only question is how to now pass it on to the underlying classes. We are not using globals in this scenario so it could be just passed in during class initialization and calls to `request_retry` would look like `request_retry(verify=self.verify).get(url)`

The fact that we even specified that it should be disabled by default in our original function is also handy, this is what I used to get over the continuous ConnectionResetError I was experiencing. What do you guys think?

**Comment by DeKaN** [comment]
Are we need retry for download? @vn-ki What do you think?

**Comment by ngomile** [comment]
To clarify, the retry isn't for downloads, it's in case getting a request from the server happens to fail and you need a way to ask again for whatever resource you want.

**Comment by vn-ki** [comment]
What @ngomile said is what I had in mind (I had been planning on doing it for quite some time). But I figured quite a lot of refactoring should come with it. (For example, we should do the same for cfscrape too). 

If you are up to the task then feel free to do it @DeKaN. Else you can skip retries and just implement the ssl part for now.

**Comment by DeKaN** [comment]
@vn-ki I've implemented ssl part. I think retries may be added later

**Comment by vn-ki** [comment]
Can someone test these changes? @ngomile @freddiaN 

I can't test it in my network.

**Comment by vn-ki** [comment]
Also @DeKaN, just trying a basic download using twist.moe gives me ConnectionResetByPeer.

**Comment by DeKaN** [comment]
@vn-ki I've tried to download something from twist.moe :

```
(venv) C:\Users\DeKaN>anime dl -u --provider=twist.moe --disable-ssl hero
[32manime[0m: anime-downloader 3.5.0
c:\users\dekan\virtualenv\venv\lib\site-packages\urllib3\connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
 1: Boku no Hero Academia
 2: Boku no Hero Academia 2nd Season
 3: Boku no Hero Academia 3rd Season
 4: High School DxD Hero
 5: Hitorijime My Hero

Enter the anime no:  [1]: 5
[32manime[0m: Selected Hitorijime My Hero
[32manime[0m: Extracting episode info from page
c:\users\dekan\virtualenv\venv\lib\site-packages\urllib3\connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[32manime[0m: Found anime: hitorijime-my-hero
[32manime[0m: Downloading to C:\Users\DeKaN\
[32manime[0m: Downloading hitorijime-my-hero-1
[32manime[0m: .\hitorijime-my-hero/hitorijime-my-hero_1.mp4
c:\users\dekan\virtualenv\venv\lib\site-packages\urllib3\connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
c:\users\dekan\virtualenv\venv\lib\site-packages\urllib3\connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Downloaded: 6.06MB/272.10MB, Rate: 2644.26KB/s
Aborted!
```

**Comment by vn-ki** [comment]
Can you try with ssl?

**Comment by DeKaN** [comment]
I've checked from another PC

After installing `pycrypto` it works:
```
(env) dekan@dekan-PC:~$ anime dl --provider=twist.moe hero
anime: anime-downloader 3.5.0
 1: Boku no Hero Academia                                           
 2: Boku no Hero Academia 2nd Season                                
 3: Boku no Hero Academia 3rd Season                                
 4: High School DxD Hero                                            
 5: Hitorijime My Hero                                              

Enter the anime no:  [1]: 5
anime: Selected Hitorijime My Hero
anime: Extracting episode info from page
anime: Found anime: hitorijime-my-hero
anime: Downloading to /home/dekan
anime: Downloading hitorijime-my-hero-1
anime: ./hitorijime-my-hero/hitorijime-my-hero_1.mp4
Downloaded: 1.23MB/272.10MB, Rate: 1059.08KB/s     
Aborted!
```

**Comment by ngomile** [comment]
I have not tried this code out but I do have to say it seems very hacky, 13 files changed with the addition of a new file to support disabling ssl. We can do better and I have suggestions.

**Comment by vn-ki** [comment]
I don't care about the number of changed files. request has to be replaced
with session.

Feel free to review the PRb if you have suggestions.

**Comment by DeKaN** [comment]
@vn-ki Fixed :)

**Comment by DeKaN** [comment]
I think it is not good idea to create global variable for file.

**Comment by DeKaN** [comment]
Ok, I'll extract to variable, if `session.get_session()` used more than once at file

**Comment by ngomile** [comment]
demo_1
demo_2
demo_3

I've basically been doing what's in the images, aliasing the imports causes less trouble but I want to see where this goes.

**Comment by DeKaN** [comment]
@ngomile I think, that your alias adds more problems for people who will read the code. It will be better to use alias `session` instead of `requests`

**Comment by vn-ki** [comment]
I'm happy with the PR as it is right now.

Retries can be a separate PR.

This was a very much needed refactoring, thanks @DeKaN for your help.

**Comment by DeKaN** [comment]
@vn-ki Are you planning to add flake8/pylint check to your project?

**Pull request merged**
