### PR TITLE
Delete kissanime.py

### PR DESCRIPTION
**Pull request by aadityaaryal**
doing what needed to be done. dont add clone sites, the stie is dead and gone, let it rest in peace.

### CODE REVIEW

**Comment by MichaelDavidJohnson** [comment]
Currently, there's a conversation going on about flat out removing dead sites or moving the python file into another dir that doesn't get transferred to the user. I would prefer the former as well as @AbdullahM0hamed  but @Blatzar prefers the latter.

**Comment by Blatzar** [comment]
As long as the .py files are easily accesible without having to look in git history I'm fine :)

**Comment by MichaelDavidJohnson** [comment]
About not adding clone sites, if they have the library of kiss and they are able to be scraped then we *are* going to add them. We are not loyal to a website that is dead. A website is merely a website.

**Comment by aadityaaryal** [comment]
guys i hope you dont merge this, i haven't changed the init file or anything else. i just deleted  the kissanime.py file lol

**Comment by MichaelDavidJohnson** [comment]
Are you planning to do anything with this PR?

**Comment by aadityaaryal** [comment]
dont know, maybe make a new one where i properly remove kissanime or do i just close it?

**Comment by MichaelDavidJohnson** [comment]
Closing, we're thinking of doing some restructuring to keep it out the project but in the Github. If you're in the Discord I'm more than happy for you to come throw your ideas out and then submit another PR

**Comment by AbdullahM0hamed** [comment]
@aaditaaryal, feel my frustration😭😭😭😭

**Pull request closed without merging**
