### PR TITLE
Reduce fake mouse movements being sent

### PR DESCRIPTION
**Pull request by AbdullahM0hamed**
Hcaptcha was sending more mouse movement data than they seem to care about, and I naively believed what I saw.

I'm here to rectify my foolish mistakes.

### CODE REVIEW

**Comment by ngomile** [comment]
Have you tried using this solution on vidstream? It might work, could become a useful utility function.

**Comment by AbdullahM0hamed** [comment]
Can't find any vidstream links with hcaptcha at the moment, know of any?

**Comment by ngomile** [comment]
Try this [link to Trinity Blood](https://vidstreaming.io/download?id=MjU1MDY=&typesub=Gogoanime-SUB&title=Trinity+Blood+Episode+1) out. Should immediately show hcaptcha or perhaps its picky.

**Comment by Blatzar** [comment]
CAPTCHAs show on vidstream if you press the download button, not stream. Trying to bypass vidstream CAPTCHAs isn't worth the effort and future problems IMO as it already works.

**Pull request closed without merging**
