### PR TITLE
Replace Pycryptodome

### PR DESCRIPTION
**Pull request by nate-moo**
uses pyaes instead of pycryptodome for full compatibility

### CODE REVIEW

**Comment by nate-moo** [comment]
Stopped working

**Comment by nate-moo** [comment]
ok, so the encrypted ciphertext length is 32 but it needs to be 16

**Comment by nate-moo** [comment]
ready for testing and 90% sure it works

**Comment by vn-ki** [comment]
This will break things for AUR and brew users.

**Comment by vn-ki** [comment]
Also looks like pyaes package isn't maintained anymore (last update 3 years ago).

**Comment by MichaelDavidJohnson** [comment]
Yeah I think the best way to deal with this is just making an ios fork, the question is should we add the fork as a fork of anime-dl?

**Pull request closed without merging**
